<a href="https://colab.research.google.com/github/Packetouille/machine-learning-research/blob/main/Data_Sceince_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Alice', 'David', 'Alice'],
    'Age': [25, 30, 28, 40, 35],
    'Gender': ['Female', 'Male', 'Female', 'Male', 'Female'],
    'City': ['New York', 'London', 'New York', 'Paris', 'New York']
}

df = pd.DataFrame(data)

print(f"Original DataFrame: \n{df}")

Original DataFrame:
    Name  Age  Gender      City
0  Alice   25  Female  New York
1    Bob   30    Male    London
2  Alice   28  Female  New York
3  David   40    Male     Paris
4  Alice   35  Female  New York

In [10]:
# Remove duplicate rows based on the 'Name' column, keeping the last occurrence, reset the index of resulting DataFrame
# NOTE: There may be cases where you DO NOT want to reindex. Such as if the indices represent unique identifiers for
# participants in a study.

df_cleaned = df.drop_duplicates(subset=['Name'], keep='last', ignore_index=True)
print(f"\nDataFrame after removing duplicates (keeping last occurrence of 'Name'):\n{df_cleaned}")

DataFrame after removing duplicates (keeping last occurrence of 'Name'):
    Name  Age  Gender      City
0    Bob   30    Male    London
1  David   40    Male     Paris
2  Alice   35  Female  New York

In [12]:
# Sample DataFrame with specific indices
data = {
    'ID': [101, 102, 101, 103, 101],
    'Name': ['Alice', 'Bob', 'Alice', 'David', 'Alice'],
    'Age': [25, 30, 25, 35, 25],
    'City': ['New York', 'Los Angeles', 'New York', 'Chicago', 'New York']
}

df = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame:")
print(df)

# Remove duplicate rows based on the 'Name' column, keeping the last occurrence
df_cleaned = df.drop_duplicates(subset=['Name'], keep='last')

# Display the DataFrame after removing duplicates without resetting the index
print("\nDataFrame after removing duplicates (keeping last occurrence of 'Name') without resetting index:")
print(df_cleaned)

Original DataFrame:
    ID   Name  Age         City
0  101  Alice   25     New York
1  102    Bob   30  Los Angeles
2  101  Alice   25     New York
3  103  David   35      Chicago
4  101  Alice   25     New York

DataFrame after removing duplicates (keeping last occurrence of 'Name') without resetting index:
    ID   Name  Age         City
1  102    Bob   30  Los Angeles
3  103  David   35      Chicago
4  101  Alice   25     New York

In [14]:
# Sample DataFrame with specific indices and some missing
data = {
    'ID': [101, None, 101, None, 101, 106],
    'Name': ['Alice', 'Bob', 'Alice', 'David', 'Alice', 'Michael'],
    'Age': [25, 30, 25, 35, 25, 28],
    'City': ['New York', 'Los Angeles', 'New York', 'Chicago', 'New York', 'Boston']
}

df = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame:")
print(df)

# Generate new unique IDs for rows with missing IDs.
max_existing_id = df['ID'].max()

# Calculate the new unique IDs starting from the next integer
new_id_sequence = range(int(max_existing_id) + 1, int(max_existing_id) + 1 + df['ID'].isna().sum())

print(f"new_id_sequence: {new_id_sequence}")

# Assign new unique IDs to rows with missing IDs
df.loc[df['ID'].isna(), 'ID'] = new_id_sequence

Original DataFrame:
      ID     Name  Age         City
0  101.0    Alice   25     New York
1    NaN      Bob   30  Los Angeles
2  101.0    Alice   25     New York
3    NaN    David   35      Chicago
4  101.0    Alice   25     New York
5  106.0  Michael   28       Boston
new_id_sequence: range(107, 109)

In [22]:
import os
import csv
path = "/content/sample_data/movies.csv"
f = os.path.normpath(path)
df = pd.read_csv(f)
df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN

In [34]:
filtered_df_rating = df[df['RATING'].notna()]
print(f"filtered_df_rating where 'RATING' is not null \n{filtered_df_rating['RATING']}")

nan_count = df['RATING'].isna().sum()
print(f"Number of NaN values in 'RATING' column: {nan_count}")

filtered_df_rating where 'RATING' is not null
0       6.1
1       5.0
2       8.2
3       9.2
5       7.6
       ...
9960    7.1
9961    6.9
9962    7.1
9963    8.2
9979    8.8
Name: RATING, Length: 8179, dtype: float64
Number of NaN values in 'RATING' column: 1820